### ISSUE TITLE
Problems with recursion

### ISSUE THREAD

**Issue by linux-admin0001** [Ttimofeyka/Rave#11]
```
import <std/io>

int fibonacci(int num) {
    if (num == 1 || num == 2) {
        return 1;
    }
    return fibonacci(num - 1) + fibonacci(num + 2);
}

void main {
    fibonacci(10);
}
```

I wrote this code, I get seg fault:
![image](https://user-images.githubusercontent.com/73735838/215272391-b66fcd16-231a-428c-8cbc-d6529c0d3f07.png)

**Comment by linux-admin0001** [comment]
But this code compilling with succes:
```
import <std/io>

void recfunc(int level) {
    if (level > 0) {
        std::println(level);
        recfunc(level - 1);
    }
}

void main {
    std::println(recfunc(10));
}
```
![image](https://user-images.githubusercontent.com/73735838/215272546-0f9fdfe3-1a64-46f8-ac83-6ba3e1bc18c2.png)

**Comment by Ttimofeyka** [comment]
int fibonacci(int num) {
            int result = 1;
            if((num != 1) && (num != 2)) {
                    result = fibonacci(num - 1) + fibonacci (num + 2);
            }
    } => result;

**Comment by linux-admin0001** [comment]
![image](https://user-images.githubusercontent.com/73735838/215274037-41d742c6-76fa-48af-baec-242f1af82365.png)

**Comment by linux-admin0001** [comment]
this doesnt work

**Comment by linux-admin0001** [comment]
yes, and your code is terrible

**Comment by Ttimofeyka** [comment]
int fib(int n) {
    if(n <= 1) {return n;}
    return fib(n - 1) + fib(n - 2);
}

**Comment by linux-admin0001** [comment]
why can't I implement the fibonacci function properly

**Comment by linux-admin0001** [comment]
> int fib(int n) {
> if(n <= 1) {return n;}
> return fib(n - 1) + fib(n - 2);
> }

this works

**Comment by linux-admin0001** [comment]
```
import <std/io>

int fibonacci(int num) {
    if (num == 1 || num == 2) {
        return 1;
    }
    return fibonacci(num + 1) + fibonacci(num + 2);
}

void main {
    std::println("fibonacci of 10: ", fibonacci(10));
}
```

**Comment by linux-admin0001** [comment]
I fixed error in my code

**Comment by linux-admin0001** [comment]
was:  `return fibonacci(num - 1) + fibonacci(num + 2);`
now: `return fibonacci(num + 1) + fibonacci(num + 2);`

**Comment by linux-admin0001** [comment]
thanks

**Comment by Ttimofeyka** [comment]
Can you send a new pull request with the correct code?

**Comment by linux-admin0001** [comment]
maybe it would be worth adding a message about reaching the maximum recursion depth?

**Comment by linux-admin0001** [comment]
> Can you send a new pull request with the correct code?

yes, second

**Comment by linux-admin0001** [comment]
> was: `return fibonacci(num - 1) + fibonacci(num + 2);` now: `return fibonacci(num - 1) + fibonacci(num - 2);`

* edited

**Comment by linux-admin0001** [comment]
I have opened a pull request
