### ISSUE TITLE
Порт на llvm-15

### ISSUE THREAD

**Issue by Domaman202** [Ttimofeyka/Rave#17]
Обещаю не возвращаться в дискорд пока Rave не портируют на llvm 15.

**Comment by KsontiPy** [comment]
Долго ждать прийдется

**Comment by Ttimofeyka** [comment]
Извините, но в ближайших планах отсутствует перенос Rave на LLVM-15.

Это невозможно в ближайшей перспективе в связи со сложностью переноса - многое нужно будет писать с нуля, что займёт продолжительное количество времени.

Во всяком случае, были рады быть с вами знакомы!
