### ISSUE TITLE
Problem with std::syscall on AARCH64 (and probably ARM)

### ISSUE THREAD

**Issue by Ttimofeyka** [Ttimofeyka/Rave#21]
There is now an error in our previous (non-extern) implementation of std::syscall for aarch64.

```
            (vararg) void* syscall(int number) {
                bool fix;
                asm(
                "
                    mov x8, x1
                    mov x1, x2
                    mov x2, x3
                    mov x3, x4
                    mov x4, x5
                    mov x5, x6
                    svc #0

                    ldr x1, =\"_RaveGstd::__syscResult\"
                    str x0, [x1]
                ");
            } => cast(void*)std::__syscResult;
```

```
            (vararg) void* syscall(int number) {
                bool fix;
                asm(
                "
                    mov w8, w0
                    mov x0, x1
                    mov x1, x2
                    mov x2, x3
                    mov x3, x4
                    mov x4, x5
                    mov x5, x6
                    svc #0

                    ldr x1, =\"_RaveGstd::__syscResult\"
                    str x0, [x1]
                ");
            } => cast(void*)std::__syscResult;
```

These code variants do not work (the first is a problem with arguments, the second is a segfault), so the libc (syscall) function is temporarily used. I hope for a quick solution to the problem.

**Comment by geckwwo** [comment]
I could try to see what's up with this tomorrow, I have 2 large assignments due tomorrow, soooo not now

**Comment by Ttimofeyka** [comment]
> I could try to see what's up with this tomorrow, I have 2 large assignments due tomorrow, soooo not now

I would be very grateful, because I couldn't fix it in a whole day, unfortunately.

**Comment by Ttimofeyka** [comment]
There may be a problem in other parts of the compiler. "i32 poison" on Rave AARCH64 appears instead of "i32 (syscall number)" on X86_64, X86 or in cross-compilation (on these platforms to AARCH64) in the LLVM IR code for the debug. Need to clarify.

**Comment by Ttimofeyka** [comment]
Temporarily resolved.
