### ISSUE TITLE
Нежелательное использование SUDO

### ISSUE THREAD

**Issue by IstsPrograms** [Ttimofeyka/Rave#23]
### В install.sh, в установке для Arch linux, sudo для yay не желательно, что говорит сам yay
![image](https://github.com/user-attachments/assets/54e9a130-e873-4b3f-9c6e-75f85164f3b4)

**Comment by Ttimofeyka** [comment]
Fixed at [this](https://github.com/Ttimofeyka/Rave/commit/0108117ecd3653a41f5dfff435ca47bfbd061e3e) commit.
