### ISSUE TITLE
readme need more info about Requirements

### ISSUE THREAD

**Issue by AndreiCherniaev** [Ttimofeyka/Rave#9]
## Requirements

* `llvm-11` (including dev-libs and clang-11)
* dub and dmd(or ldc/gdc) compiler

Please add more information about this: (including dev-libs and clang-11). 
And it is good idea to add Instruction "Install example for Ubuntu", For example:
```
sudo snap install dmd --classic
sudo snap install dmd --classic
sudo apt-get install llvm-11
```

I don't understand why in Ubuntu 22 X86_64
```
$ dub build
Performing "debug" build using dmd for x86_64.
d-glob 0.4.0: target for configuration "default" is up to date.
llvm-d 3.0.0: target for configuration "native-target" is up to date.
rave ~main: building configuration "application"...
source/parser/ast.d(1194,36): Error: template std.bigint.BigInt.opCast does not match any template declaration
source/parser/ast.d(1197,37): Error: template std.bigint.BigInt.opCast does not match any template declaration
dmd failed with exit code 1.
```

**Comment by Ttimofeyka** [comment]
Thanks for letting me know.

The error is most likely due to your dmd version.
Have you tried running install.sh or install dmd from the official website?

**Comment by AndreiCherniaev** [comment]
> Have you tried running install.sh

no, because no information about it in README.md
Usually maintainer add "How to build". [Example](https://github.com/aria2/aria2)

I plan to try install.sh in next time.

**Comment by Ttimofeyka** [comment]
Okey, i will change README.md

пн, 23 янв. 2023 г., 11:08 AndreiCherniaev ***@***.***>:

**Comment by AndreiCherniaev** [comment]
@Ttimofeyka 

please add information how to build any example. For example in C++ I should use 
`g++ main.cpp hello.cpp factorial.cpp -o hello`

And It's bad idea to have example code in README.md and haven't the same in Rave/examples/

**Comment by Ttimofeyka** [comment]
Ok, I will do that. Thanks

вт, 24 янв. 2023 г., 09:01 AndreiCherniaev ***@***.***>:

**Comment by AndreiCherniaev** [comment]
> Ok, I will do that.

"After install write dub build in the project directory." it is bad idea for readme. project directory? Which project? I just want to build first example first.rave. MySteps is:
#install Rave
$ ./install.sh 

[ Rave Installer ] Installing LLVM-11
[sudo] password for a: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
clang-11 is already the newest version (1:11.1.0-6).
libllvm11 is already the newest version (1:11.1.0-6).
lldb-11 is already the newest version (1:11.1.0-6).
llvm-11 is already the newest version (1:11.1.0-6).
llvm-11-dev is already the newest version (1:11.1.0-6).
llvm-11-runtime is already the newest version (1:11.1.0-6).
0 upgraded, 0 newly installed, 0 to remove and 12 not upgraded.
[ Rave Installer ] Successfully installed LLVM-11.
[ Rave Installer ] Installing DMD
dmd-2.101.2 already installed
Using dub 1.30.0 shipped with dmd-2.101.2

Run `source ~/dlang/dmd-2.101.2/activate` in your shell to use dmd-2.101.2.
This will setup PATH, LIBRARY_PATH, LD_LIBRARY_PATH, DMD, DC, and PS1.
Run `deactivate` later on to restore your environment.
[ Rave Installer ] Successfully installed DMD.
[ Rave Installer ] Done.

$ cd examples/ && dub build

Neither a package description file, nor source/app.d was found in
/home/a/Downloads/myGitHub/Rave/examples
Please run DUB from the root directory of an existing package, or run
"dub init --help" to get information on creating a new package.

**No valid root package found - aborting.**

**Comment by Ttimofeyka** [comment]
The README states that you must first compile Rave itself - that's what
these commands and installers are for.
Examples can be compiled via "rave test.rave -o test".

ср, 25 янв. 2023 г., 05:20 AndreiCherniaev ***@***.***>:

**Comment by AndreiCherniaev** [comment]
> The README states that you must first compile Rave itself - that's what these commands and installers are for.

```
$ ./install.sh
[ Rave Installer ] Installing LLVM-11
[sudo] password for a: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
clang-11 is already the newest version (1:11.1.0-6).
libllvm11 is already the newest version (1:11.1.0-6).
lldb-11 is already the newest version (1:11.1.0-6).
llvm-11 is already the newest version (1:11.1.0-6).
llvm-11-dev is already the newest version (1:11.1.0-6).
llvm-11-runtime is already the newest version (1:11.1.0-6).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
[ Rave Installer ] Successfully installed LLVM-11.
[ Rave Installer ] Installing DMD
dmd-2.101.2 already installed
Using dub 1.30.0 shipped with dmd-2.101.2

Run `source ~/dlang/dmd-2.101.2/activate` in your shell to use dmd-2.101.2.
This will setup PATH, LIBRARY_PATH, LD_LIBRARY_PATH, DMD, DC, and PS1.
Run `deactivate` later on to restore your environment.
[ Rave Installer ] Successfully installed DMD.
[ Rave Installer ] Done.
```

Looks ok.

```
$ dub build
Performing "debug" build using dmd for x86_64.
d-glob 0.4.0: building configuration "default"...
llvm-d 3.0.0: building configuration "native-target"...
rave ~main: building configuration "application"...
source/parser/ast.d(1194,36): Error: template std.bigint.BigInt.opCast does not match any template declaration
source/parser/ast.d(1197,37): Error: template std.bigint.BigInt.opCast does not match any template declaration
dmd failed with exit code 1.
```

Ubuntu 22 x86_64

**Comment by Ttimofeyka** [comment]
Try executing `source ...`.
If that doesn't work, you can try to remove the dmd and install the ldc from apt.

**Comment by AndreiCherniaev** [comment]
> Try executing `source ...`.
> If that doesn't work, you can try to remove the dmd and install the ldc from apt.

Rave$ source ...
bash: ...: No such file or directory

**Comment by Ttimofeyka** [comment]
> > Try executing `source ...`.
> > If that doesn't work, you can try to remove the dmd and install the ldc from apt.
> 
> ```
> Rave$ source ...
> bash: ...: No such file or directory
> ```

"source" is not a separate program in Linux.
You can use this command by running the "sudo -s" command first.

**Comment by AndreiCherniaev** [comment]
> "source" is not a separate program in Linux. You can use this command by running the "sudo -s" command first.
```

Rave$ sudo -s
[sudo] password for a: 
root@desktop:/home/Rave# 
root@desktop:/home/Rave# source ...
bash: ...: No such file or directory
```

**Comment by Ttimofeyka** [comment]
I meant that you have to execute the command that was written when installing the DMD in install.sh, but I'm glad you solved the problem.
